move script77.erm "1 wog - cheat menu.erm"
move script77.ert "1 wog - cheat menu.ert"
move script76.erm "2 wog - commander sanctuary.erm"
move script76.ert "2 wog - commander sanctuary.ert"
move script75.erm "3 wog - secondary skill text.erm"
move script75.ert "3 wog - secondary skill text.ert"
move script74.erm "4 wog - summon elementals.erm"
move script74.ert "4 wog - summon elementals.ert"
move script73.erm "5 wog - enhanced war machines 3.erm"
move script73.ert "5 wog - enhanced war machines 3.ert"
move script72.erm "6 wog - random hero.erm"
move script71.erm "7 wog - enhanced artifacts.erm"
move script71.ert "7 wog - enhanced artifacts.ert"
move script70.erm "8 wog - death chamber.erm"
move script70.ert "8 wog - death chamber.ert"
move script69.erm "9 wog - custom alliances.erm"
move script69.ert "9 wog - custom alliances.ert"
move script68.erm "10 wog - new battlefields.erm"
move script67.erm "11 wog - neutral town.erm"
move script67.ert "11 wog - neutral town.ert"
move script66.erm "12 wog - commander witch huts.erm"
move script66.ert "12 wog - commander witch huts.ert"
move script65.erm "13 wog - monolith costs.erm"
move script65.ert "13 wog - monolith costs.ert"
move script64.erm "14 wog - tobyn's scripts.erm"
move script64.ert "14 wog - tobyn's scripts.ert"
move script63.erm "15 wog - passable terrain.erm"
move script63.ert "15 wog - passable terrain.ert"
move script62.erm "16 wog - split decision.erm"
move script62.ert "16 wog - split decision.ert"
move script61.erm "17 wog - protection from the elements.erm"
move script60.erm "18 wog - forgotten shrine.erm"
move script60.ert "18 wog - forgotten shrine.ert"
move script59.erm "19 wog - piercing shot.erm"
move script59.ert "19 wog - piercing shot.ert"
move script58.erm "20 wog - espionage.erm"
move script58.ert "20 wog - espionage.ert"
move script57.erm "21 wog - neutral units.erm"
move script57.ert "21 wog - neutral units.ert"
move script56.erm "22 wog - metamorphs.erm"
move script56.ert "22 wog - metamorphs.ert"
move script55.erm "23 wog - enhanced war machines 2.erm"
move script55.ert "23 wog - enhanced war machines 2.ert"
move script54.erm "24 wog - enhanced war machines 1.erm"
move script54.ert "24 wog - enhanced war machines 1.ert"
move script53.erm "25 wog - dungeon of the dragonmaster.erm"
move script53.ert "25 wog - dungeon of the dragonmaster.ert"
move script52.erm "26 wog - mirror of the home-way.erm"
move script52.ert "26 wog - mirror of the home-way.ert"
move script51.erm "27 wog - enhanced commanders.erm"
move script51.ert "27 wog - enhanced commanders.ert"
move script50.erm "28 wog - enhanced monsters.erm"
move script50.ert "28 wog - enhanced monsters.ert"
move script49.erm "29 wog - henchmen.erm"
move script49.ert "29 wog - henchmen.ert"
move script48.erm "30 wog - enhanced secondary skills.erm"
move script48.ert "30 wog - enhanced secondary skills.ert"
move script47.erm "31 wog - creature relationships.erm"
move script47.ert "31 wog - creature relationships.ert"
move script46.erm "32 wog - berserker flies.erm"
move script46.ert "32 wog - berserker flies.ert"
move script45.erm "33 wog - castle upgrading.erm"
move script45.ert "33 wog - castle upgrading.ert"
move script44.erm "34 wog - emerald tower.erm"
move script44.ert "34 wog - emerald tower.ert"
move script43.erm "35 wog - obelisk runes.erm"
move script43.ert "35 wog - obelisk runes.ert"
move script42.erm "36 wog - garrisons.erm"
move script42.ert "36 wog - garrisons.ert"
move script41.erm "37 wog - battle extender.erm"
move script40.erm "38 wog - first money.erm"
move script39.erm "39 wog - hero specialization boost.erm"
move script39.ert "39 wog - hero specialization boost.ert"
move script38.erm "40 wog - karmic battles.erm"
move script37.erm "41 wog - rebalanced factions.erm"
move script37.ert "41 wog - rebalanced factions.ert"
move script36.erm "42 wog - mithril enhancements.erm"
move script36.ert "42 wog - mithril enhancements.ert"
move script35.erm "43 wog - mysticism skill enhancement.erm"
move script35.ert "43 wog - mysticism skill enhancement.ert"
move script34.erm "44 wog - cards of prophecy.erm"
move script34.ert "44 wog - cards of prophecy.ert"
move script33.erm "45 wog - living scrolls.erm"
move script33.ert "45 wog - living scrolls.ert"
move script32.erm "46 wog - summoning stones.erm"
move script32.ert "46 wog - summoning stones.ert"
move script31.erm "47 wog - treasure chest 2.erm"
move script31.ert "47 wog - treasure chest 2.ert"
move script30.erm "48 wog - adventure cave.erm"
move script30.ert "48 wog - adventure cave.ert"
move script29.erm "49 wog - chest.erm"
move script29.ert "49 wog - chest.ert"
move script28.erm "50 wog - school of wizardry.erm"
move script28.ert "50 wog - school of wizardry.ert"
move script27.erm "51 wog - spell book.erm"
move script27.ert "51 wog - spell book.ert"
move script26.erm "52 wog - artificer.erm"
move script26.ert "52 wog - artificer.ert"
move script25.erm "53 wog - map options.erm"
move script25.ert "53 wog - map options.ert"
move script24.erm "54 wog - enhanced dwelling hint text.erm"
move script24.ert "54 wog - enhanced dwelling hint text.ert"
move script23.erm "55 wog - sorcery skill enhancement.erm"
move script23.ert "55 wog - sorcery skill enhancement.ert"
move script22.erm "56 wog - monster mutterings.erm"
move script22.ert "56 wog - monster mutterings.ert"
move script21.erm "57 wog - freelancers guild.erm"
move script21.ert "57 wog - freelancers guild.ert"
move script20.erm "58 wog - week of monsters.erm"
move script20.ert "58 wog - week of monsters.ert"
move script19.erm "59 wog - masters of life.erm"
move script18.erm "60 wog - alms house.erm"
move script18.ert "60 wog - alms house.ert"
move script17.erm "61 wog - potion fountains.erm"
move script17.ert "61 wog - potion fountains.ert"
move script16.erm "62 wog - battle academy.erm"
move script16.ert "62 wog - battle academy.ert"
move script15.erm "63 wog - mysterious creature dwelling.erm"
move script15.ert "63 wog - mysterious creature dwelling.ert"
move script14.erm "64 wog - altar of transformation.erm"
move script14.ert "64 wog - altar of transformation.ert"
move script13.erm "65 wog - tavern gambling game.erm"
move script13.ert "65 wog - tavern gambling game.ert"
move script12.erm "66 wog - living skull.erm"
move script12.ert "66 wog - living skull.ert"
move script11.erm "67 wog - palace of dreams.erm"
move script11.ert "67 wog - palace of dreams.ert"
move script10.erm "68 wog - magic mushrooms.erm"
move script10.ert "68 wog - magic mushrooms.ert"
move script09.erm "69 wog - market of time.erm"
move script09.ert "69 wog - market of time.ert"
move script08.erm "70 wog - junk merchant.erm"
move script08.ert "70 wog - junk merchant.ert"
move script07.erm "71 wog - fishing well.erm"
move script07.ert "71 wog - fishing well.ert"
move script06.erm "72 wog - hourglass of asmodeus.erm"
move script06.ert "72 wog - hourglass of asmodeus.ert"
move script05.erm "73 wog - bank.erm"
move script05.ert "73 wog - bank.ert"
move script04.erm "74 wog - arcane tower.erm"
move script04.ert "74 wog - arcane tower.ert"
move script03.erm "75 wog - secondary skills boost.erm"
move script03.ert "75 wog - secondary skills boost.ert"
move script02.erm "76 wog - artifact boost.erm"
move script02.ert "76 wog - artifact boost.ert"
move script01.erm "77 wog - map rules.erm"
move script01.ert "77 wog - map rules.ert"
move script00.erm "78 wog - wogify.erm"
move script00.ert "78 wog - wogify.ert"
pause